const Map<String, String> zh = {
  'interactiveViewer': '菜单栏',
  'drawerHeader': '侧边栏',
  'saveToDataDir': '保存到数据目录',
  'open': '打开',
  'new': '新建',
  'save': '保存',
  'createRelatedNode': '创建相关节点',
  'createParentNode': '创建父节点',
  'createChildNode': '创建子节点',
  'fontSize': '字体大小',
  'fontStyle': '字体风格',
  'randomTheme': '随机主题',
  'increment': '新增',
  'screenshot': '截图',
  'aiChat': 'AI聊天',
  'aiApiIllustrate': '找不到API密钥。请使用“--dart-define”设置“API_Key”声明提供API密钥。',
  'enterAPrompt': '输入提示...',
};
